# Generated by Django 4.2.4 on 2023-08-28 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200)),
                ('productid', models.CharField(max_length=200)),
                ('orderid', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('productprice', models.CharField(max_length=200)),
                ('totalprice', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoryname', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='categoryimage')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True, auto_now=True)),
                ('userid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('productid', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('paymentmethod', models.CharField(max_length=200)),
                ('transactionid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Userregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('MobileNumber', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('CPassword', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=200)),
                ('Price', models.CharField(max_length=200)),
                ('Quantity', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='productimage')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jagruti.category')),
            ],
        ),
    ]
