# Generated by Django 4.2.4 on 2023-09-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jagruti', '0004_remove_shipping_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='datetime',
        ),
    ]
