# Generated by Django 4.2.4 on 2023-09-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagruti', '0005_remove_cart_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='datetime',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
